version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-pg
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"