version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: