from .fill_categories import add_categories
from .fill_chassis import add_chassis
from .fill_engines import add_engines
from .fill_factories import add_factories
from .fill_users import add_users
from .fill_wheels import add_wheel_formulas
from .fill_vehicles import add_vehicles
from .fill_price_list import add_price_list
from .fill_requests import add_requests
from .fill_requisitioned_goods import add_requisitioned_goods
from .fill_news import add_news